name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nikunjthebest/fastapi-cicd-pipeline-on-cloud-vm:latest
    - name: Delete Old docker container
      run: sudo docker rm -f fastapi-cicd-pipeline-on-cloud-vm || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name fastapi-cicd-pipeline-on-cloud-vm nikunjthebest/fastapi-cicd-pipeline-on-cloud-vm